categories: [Transcriptomics]
description: SMAGEXP (Statistical Meta Analalysis for Gene EXPression) for galaxy
long_description: 'SMAGEXP (Statistical Meta Analalysis for Gene EXPression) integrates
  metaMA and metaRNAseq packages into Galaxy. We aim to propose a unified way to carry
  out meta-analysis of gene expression data, while taking care of their specificities.

  We have developed this tool suite to analyse microarray data from Gene Expression
  Omnibus (GEO) database or custom data from affymetrix microarrays. These data are
  then combined to carry out meta-analysis using metaMA package. SMAGEXP also offers
  to combine raw read counts from Next Generation Sequencing (NGS) experiments using
  DESeq2 and metaRNASeq package. In both cases, key values, independent from the technology
  type, are reported to judge the quality of the meta-analysis.'
name: smagexp
owner: sblanck
